### ISSUE TITLE
Passing options to DataSourcer

### ISSUE THREAD

**Issue by stylesuxx** [chill117/proxy-lists#100]
It would be great to pass options to the `DataSourcer` - especially regarding options for _puppeteer_.

**Comment by chill117** [comment]
I want to do this, but it requires changes to the way ProxyLists is loaded by the user. So it would require a major version bump (2.x.x). Do you have an idea for the API/interface?

**Comment by stylesuxx** [comment]
I am not sure it really does - when invoking the getProxies method you are passing options can't we pass options to be passed to DataSourcer here?

**Comment by chill117** [comment]
> I am not sure it really does - when invoking the getProxies method you are passing options can't we pass options to be passed to DataSourcer here?

No, because the DataSourcer instance is created at run-time when the ProxyLists module is required:
https://github.com/chill117/proxy-lists/blob/9bdf31f0cad522ae8f8376ca1a0917d4d30304e6/index.js#L13-L19

**Comment by stylesuxx** [comment]
I see. How about a method that overrides the sourcer attribute:

```js
setSourcer: function(options) {
  const defaults = {
    getDataMethodName: 'getProxies',
    sourcesDir: process.env.PROXY_LISTS_SOURCES_DIR || path.join(__dirname, 'sources'),
  };

  this.sourcer = new DataSourcer(Object.assign({}, defaults, options));
},
```

**Comment by chill117** [comment]
Can now pass options to [dataSourcer](https://github.com/chill117/data-sourcer#getdata) when calling `getProxies` and `getProxiesFromSource`. Most relevant options:
* `browser` - Options object passed to [puppeteer.launch(options)](https://pptr.dev/#?product=Puppeteer&version=v1.19.0&show=api-puppeteerlaunchoptions)
* `sourcesDir` - Directory path where your sources are defined. Default is the "sources" directory included with the ProxyLists project.
