### ISSUE TITLE
CLI: Running out of memory while running in VPS

### ISSUE THREAD

**Issue by salesiss** [chill117/proxy-lists#105]
After serving for years with enormous contribution proxy-lists stopped giving results today-suddenly. Problems started aproximatly last february 1st, 2020. For testing pourpouses, we started a new instance of:

Spun new Ubuntu 19.10 vps, on vultr.com (1gbram,25ssd)

We did:

```
    2  apt update
    3  apt install npm
    5  apt install nano npm git htop curl wget
    6  apt install nodejs
   11  cd /home
   12  git clone https://github.com/chill117/proxy-lists.git
   23  npm install
   25  node .
   26  ls -ltr
   27  . /cli.js
   28  . /cli.js getProxies --stdout
```

node --version: v10.15.2
npm --version: 5.8.0

Results:

root@vultrmia1:/home/proxy-lists# . /cli.js
root@vultrmia1:/home/proxy-lists# . /cli.js getProxies --stdout
(node:10422) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 SIGINT listeners added. Use emitter.setMaxListeners() to increase limit
(node:10422) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 exit listeners added. Use emitter.setMaxListeners() to increase limit
(node:10422) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 SIGTERM listeners added. Use emitter.setMaxListeners() to increase limit
(node:10422) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 SIGHUP listeners added. Use emitter.setMaxListeners() to increase limit

**and NO DATA, no results anymore..**

our knwoledge of node ends here (installation, simple fixes). If anyone can help or explain this behaviour. we will be GLAD !! thank you.

**Comment by salesiss** [comment]
Wich error messages are we getting ?

1. Those related to pupetter/chrome not installing. Solved  with:
#npm install -g proxy-lists --unsafe-perm=true --allow-root

2. Related to sandbox. Solved with:
create user #useradd run001 #mkdir /home/run001 #chown -R run001:run001 /home/run001
run program #runuser -l run001 -c 'proxy-lists getProxies --stdout'

3. Related to chrome/pupetter (timeouts,etc)- UNSOLVED !
so we think problems can be much more pupetter/chrome related than related to proxy-lists itself.

4. here is the current log:
[proxy-lists-chrome-problems.log](https://github.com/chill117/proxy-lists/files/4183881/proxy-lists-chrome-problems.log)

5. we have detected that proxy-lists spawn 200-300 threads and most vps run out of memory. It now uses easily 1GB-2GB of ram. Tested both with ubuntu 18.04.3 LTS and with ubuntu 19.10 - memory is getting quiclky exhausted.

**Comment by chill117** [comment]
Hello, @salesiss. It sounds like the program is running out of memory. For each proxy list that is scraped, a new chrome tab is created via puppeteer. By default this is done asynchronously. So in the worst case there could be dozens of tabs open simultaneously. To prevent this, you can pass `--series` to the CLI command. This will run all operations in series instead of in parallel. Hope that helps!

**Comment by salesiss** [comment]
Thank you chil117, it worked. It's been running now for a month without issues. 

An example may follow as we used --sources-white-list=bitproxies.js ; --sources-white-list=coolproxy.js ; --sources-white-list=bitproxies.js ; and so far, instead of --series to have better control of execution. Anyway excellent job of yours !
