### ISSUE TITLE
The country field is not being pulled

### ISSUE THREAD

**Issue by csandman** [chill117/proxy-lists#115]
I noticed the `country` field is returning null for all proxy sources.  I looked through the code and noticed this:

```js
processProxy: function(proxy) {
	proxy.country = this.lookupIpAddressCountry(proxy.ipAddress);
	return proxy;
},
lookupIpAddressCountry: function() {
	var country;

	try {
		var geo = geoip.lookup(proxy.ipAddress);
		country = geo.country && geo.country.toLowerCase();
	} catch (error) {
		debug.error(error);
	}

	return country || null;
},
```

I see the `ipAddress` field is being passed to the `lookupIpAddressCountry` function but it's not being received by the function, and in the `geoip.lookup` call its trying to pass the ip from the full proxy object.  I can't tell if this is just something I'm missing or it's supposed to be this way... but an easy fix is just to add the `ipAddress` argument and use that in the function.

```js
processProxy: function(proxy) {
	proxy.country = this.lookupIpAddressCountry(proxy.ipAddress);
	return proxy;
},
lookupIpAddressCountry: function(ipAddress) {
	var country;

	try {
		var geo = geoip.lookup(ipAddress);
		country = geo.country && geo.country.toLowerCase();
	} catch (error) {
		debug.error(error);
	}

	return country || null;
},
```

This is the only place in the package that this function is called so I can't think of any reason why this would break anything.  I can submit a pull request if you'd like, I just wanted to make sure this was actually an error before I did!

**Comment by chill117** [comment]
Fixed and will be in the next release.

**Comment by csandman** [comment]
Great, thanks for the response!
