### ISSUE TITLE
Source Not Working: hugeproxies

### ISSUE THREAD

**Issue by csandman** [chill117/proxy-lists#116]
The source huge proxies from https://hugeproxies.com/ appears to no longer be working and should possibly be removed

**Comment by csandman** [comment]
![image](https://user-images.githubusercontent.com/9214195/80647360-53fd4700-8a3c-11ea-8cce-33598481f729.png)

**Comment by chill117** [comment]
Done by 5a518032983c936dcfe3e5550771ca5be73d039c
