### ISSUE TITLE
Source Not Working: proxylists-net

### ISSUE THREAD

**Issue by csandman** [chill117/proxy-lists#118]
The rss feed for http://www.proxylists.net/ is no longer working.

![image](https://user-images.githubusercontent.com/9214195/80650935-ef91b600-8a42-11ea-9348-4791ac6b394b.png)

It would be possible to convert it to a list crawler but after looking around the site a little bit, it seems like its just out of date overall and probably not worth keeping.

**Comment by chill117** [comment]
Removed source by 9a1f096fad855ea3ad98c4a2d975b15e329cc71b
