### ISSUE TITLE
Why does this package not work on the frontend?

### ISSUE THREAD

**Issue by vladislav-puzyrev** [chill117/proxy-lists#129]
Hi. I would like to know if this package can work on the frontend via webpack? Now i get an error - "JavaScript heap out of memory". 

Thanks for you package! 🎉

**Comment by chill117** [comment]
This project is intended to be used from the CLI or from another node.js application. It is not intended to be run within a browser. As to the "why" in your question: The project uses [puppeteer](https://github.com/puppeteer/puppeteer) to gather proxies from public proxy sources, which runs a headless browser. It's not possible to run a browser in a browser.
