### ISSUE TITLE
Data event ends early or end event doesn't fire causing process to close

### ISSUE THREAD

**Issue by fbagjug** [chill117/proxy-lists#131]
After some testing and logging I watched all of the proxies come through and at one point it randomly stopped and ended the process without firing my function or the end event being called. Just wondering if anyone has a fix for this?

**Comment by chill117** [comment]
Can you please provide the application code related to this module?

**Comment by fbagjug** [comment]
```
let proxy = [];
ProxyLists.getProxies({
    protocols: ['https']
})
.on('data', (proxies) => {
     proxy.push(`${proxies[0].ipAddress}:${proxies[0].port}`);
})
.on('end', () => {
    fs.writeFile('proxies.txt', proxy, (err) => {
      if (err) return;
    })
    makeReq();
})
```

**Comment by chill117** [comment]
I've tried the code. It takes a few minutes, but the end event fires as expected.

**Comment by fbagjug** [comment]
For me it caused the process to completely end, weird 🤔

**Comment by chill117** [comment]
> For me it caused the process to completely end, weird  . Ill re-attempt not using the IDE terminal

If there is no longer any code in the event loop waiting to run, then the process will exit. That is expected behavior in node.js.

**Comment by fbagjug** [comment]
There should be code in the event loop considering I trigger a function as soon as the proxies are done scraping, to further prove my theory on it I attempted to log the end event and the log didn't come through either. I will keep testing and get back to you

**Comment by fbagjug** [comment]
![image](https://user-images.githubusercontent.com/34402846/106923365-e4706280-6705-11eb-9213-8df18fc51528.png)
![image](https://user-images.githubusercontent.com/34402846/106923452-fd791380-6705-11eb-8ea1-d4263f044380.png)

**Comment by fbagjug** [comment]
![image](https://user-images.githubusercontent.com/34402846/106924500-09190a00-6707-11eb-8dc5-9cf091a8ca03.png)
Looking at the errors that is the thing given on the process end

**Comment by fbagjug** [comment]
![image](https://user-images.githubusercontent.com/34402846/106924617-23eb7e80-6707-11eb-81c5-f0085ae30bd4.png)
This is the error given on process stop

**Comment by fbagjug** [comment]
No I'm in fact stupid I apologise
