### ISSUE TITLE
Use proxy in proxy-list

### ISSUE THREAD

**Issue by cyclops24** [chill117/proxy-lists#17]
Hi @chill117 ,
Is it possible to set proxy for proxy-list module?? For example pass proxy option through [request](https://www.npmjs.com/package/request) proxy options.
Some proxy source block my IP and I want to set proxy when use proxy-list.

**Comment by chill117** [comment]
No, this is not currently possible. But I think that's a good idea. The difficulty is that proxy-lists is divided into "sources". Each source is responsible for making the HTTP requests to pull proxy data from various websites/APIs. So it would be a decent amount of work to implement this.

**Comment by cyclops24** [comment]
@chill117 ,
Thanks for your attention. I think it's simple because request module has this feature. It's only need to set HTTP_PROXY environment variable here base on [documentation](https://www.npmjs.com/package/request#controlling-proxy-behaviour-using-environment-variables).
Did I miss something or it's work?

**Comment by cyclops24** [comment]
I test and it's work for me but I think it's more better if it's available as a property. :hand:

**Comment by chill117** [comment]
Nice work. Yes, that HTTP_PROXY environment variable is useful. Not sure when I will have time, but I'll work on adding this feature as an option for this module.

**Comment by cyclops24** [comment]
@chill117 when you want to add this new feature?? Which milestone you want doing this?

**Comment by chill117** [comment]
Apologies. I still haven't had time to tackle this yet.

**Comment by cyclops24** [comment]
@chill117 I see that request module also has a proxy option that can be used like this:

```
let proxy = "<PROXY>";
let requestOptions = {
            url: url,
            proxy: proxy
        };
```

**Comment by chill117** [comment]
A nice solution could be to add a new option for all the `getProxies` functions in this module - `requestOptions` which could be used to extend the options passed to the request module.

**Comment by rom1504** [comment]
It could also be possible to pass a request "instance" to the `getProxies` functions using request.default with proxy settings already set, see https://github.com/request/request#requestdefaultsoptions

**Comment by chill117** [comment]
I am currently working on this:
https://github.com/chill117/proxy-lists/tree/request-options

**Comment by chill117** [comment]
Done, will be included in the next release.
