### ISSUE TITLE
Save as text (export)

### ISSUE THREAD

**Issue by cyclops24** [chill117/proxy-lists#18]
Hi @chill117 ,
I guess a simple export feature maybe useful. Many people want to export this module result as a standard proxy list text file (IP:PORT).

**Comment by chill117** [comment]
@cyclops24 How about if proxy-lists could be used as a CLI tool and you could use an option to tell it to output the results to a text file. What do you think?

**Comment by cyclops24** [comment]
@chill117 I think it's useful man. It's what I want from this feature request. :smile:

**Comment by chill117** [comment]
I started working on this.

**Comment by chill117** [comment]
This is now possible (as of v1.6.0). See the [CLI section of the readme](https://github.com/chill117/proxy-lists#command-line-interface) for exact usage information.

**Comment by cyclops24** [comment]
@chill117 thanks for this new version. :wink:
