### ISSUE TITLE
Please add this two google passed proxy source

### ISSUE THREAD

**Issue by cyclops24** [chill117/proxy-lists#19]
Hi @chill117 ,
I used this two source for google passed proxy and want to suggest you:
http://www.google-proxy.net/
http://googleproxies24.blogspot.co.uk

**Comment by chill117** [comment]
Looks like the first one (http://www.google-proxy.net/) doesn't have any proxies listed.

The second one I can implement.

**Comment by chill117** [comment]
The second one redirects to a proxy list website that has already been added as a source.

**Comment by cyclops24** [comment]
@chill117 http://googleproxies24.blogspot.com redirect to which source?
