### ISSUE TITLE
blackhatworld proxies

### ISSUE THREAD

**Issue by cyclops24** [chill117/proxy-lists#26]
Hi @chill117 this forum section also has many proxy and also update daily:
http://www.blackhatworld.com/forums/proxy-lists.103/

**Comment by stylesuxx** [comment]
If you compile a list of the threads of interest, I might take a shot at it (I am not a local there, so I do not know what is of interest/good quality).

Would be cool if you could group it by protocol or even anonymity:
http/https/socks4/socks5/
transparent/anon/elite

Some kind of filtering has to happen, which proxies would we scrape from there - how far back should we go.

**Comment by cyclops24** [comment]
Hi @stylesuxx,
I listed some good quality and more active proxy threads below:
http://www.blackhatworld.com/seo/100-free-elite-proxies-every-day-new-fresh-anonymous-proxy-list.755433/page-27
http://www.blackhatworld.com/seo/new-fresh-big-proxy-lists-worldwide-usa-and-elite-proxies-updated-daily.753956/page-22
http://www.blackhatworld.com/seo/gscraper-proxies.703493/page-10
http://www.blackhatworld.com/seo/daily-proxies-all-proxy-protocols.453375/page-69
http://www.blackhatworld.com/seo/100-scrapebox-proxies.297574/page-73

**Comment by chill117** [comment]
Thanks, @cyclops24. 

I don't have much time right now, but if anyone would like to jump on this one, I'll be happy to review and merge any PRs.

**Comment by chill117** [comment]
The list at [this link](http://www.blackhatworld.com/seo/100-free-elite-proxies-every-day-new-fresh-anonymous-proxy-list.755433/page-27) is posted by MaxiProxies. So I am going to add a new source for MaxiProxies directly (which I found [here](http://maxiproxies.com/proxy-lists/)).

**Comment by chill117** [comment]
I added a new source for the blackhatworld forum. I did it in a way so that we can add new thread URLs easily. I think the format for the proxy lists posted in the forum are pretty standard. You can see the code [here](https://github.com/chill117/proxy-lists/blob/master/sources/blackhatworld.js).

**Comment by chill117** [comment]
All active blackhatworld threads mentioned here have been added.
