### ISSUE TITLE
CLI: Output format stdout

### ISSUE THREAD

**Issue by stylesuxx** [chill117/proxy-lists#33]
I was wondering if it is possible to simply write the proxies to stdout instead of a file?

I am running multiple instances in the same folder and do this for a workaround:

    cd tmp/http && proxy-lists getProxies --sources-white-list="hidemyass" --protocols="http" > /dev/null 2>&1 && cat proxies.txt

If I could write to stdout I could simply redirect the output, without this ugly construct ;-)

**Comment by chill117** [comment]
Yes, this is definitely something that should be supported -- maybe even should be the default behavior.

**Comment by stylesuxx** [comment]
If it is OK or you, I would look into it and submit a PR.

**Comment by chill117** [comment]
That would be great. Thank you :)
