### ISSUE TITLE
Test failing for proxies24

### ISSUE THREAD

**Issue by stylesuxx** [chill117/proxy-lists#35]
Pretty sure this was working last week, but the test for proxies24 is failing:

```
AssertionError: expected [ Array(1) ] to deeply equal []
      + expected - actual

      -[
      -  {
      -    "ipAddress": "838.67.208.17"
      -    "port": 45554
      -    "protocols": [
      -      "socks5"
      -    ]
      -  }
      -]
      +[]

```

This seems to be because of the invalid IP address. The proxy is pushed on the invalid proxy list. Not sure if the test should fail - I guess internally such proxies are excluded.

**Comment by chill117** [comment]
`838.67.208.17` is an invalid IP address. Some of the unit tests do pull real data from each source. So it is possible that some of the proxies published on some of the sources could be invalid.

I think ignoring these inconsistent errors is the right approach.

**Comment by stylesuxx** [comment]
For future reference, this check was the reason the test was failing:
https://github.com/chill117/proxy-lists/blob/master/test/unit/sources/index.js#L110

Maybe this should only fail in case the length of `invalidProxies` is the same as of `proxies`, ie.: all proxies are broken...

**Comment by chill117** [comment]
Thanks. That sounds reasonable.

**Comment by stylesuxx** [comment]
I can PR this change - I had it done, just did not push it since the test was not failing anymore,...

**Comment by chill117** [comment]
Sure. I think it should check that:
* Each source returns at least one proxy
* At least one of the proxies returned is valid

**Comment by stylesuxx** [comment]
https://github.com/chill117/proxy-lists/blob/master/test/unit/sources/index.js#L97

assures that at least one proxy was found, and my changes assures that not all are invalid.
