### ISSUE TITLE
TypeError: Cannot read property 'indexOf' of null

### ISSUE THREAD

**Issue by peterkorodi** [chill117/proxy-lists#43]
I've installed proxy-lists:
$ npm install -g proxy-lists

After I've got this error when I'd like to get a proxy list:
$ proxy-lists getProxies --sources-white-list="hidemyass" --stdout
TypeError: Cannot read property 'indexOf' of null

How can I get a proxy list?

**Comment by chill117** [comment]
Looks like this is a bug. I am able to reproduce the error. I'll have a look when I get some free time.

Most likely this is just a problem with the "hidemyass" proxy list, and not with the others.

**Comment by chill117** [comment]
Fixed the issue and release a new version (v1.11.0). I don't have time now, but I will revisit this to add tests for the CLI.

**Comment by peterkorodi** [comment]
It's working. Thanks
