### ISSUE TITLE
Suggestion: update code style to ES6

### ISSUE THREAD

**Issue by mnlbox** [chill117/proxy-lists#45]
Hi @chill117 ,
Thanks for this awesome tool. I suggest to update and refactor code to ES6 style. It's more clear and more robust.

**Comment by chill117** [comment]
@mnlbox Thank you for the kind words. Unfortunately, for the near-term I do not plan to migrate the code-bases that I maintain to ES6. I do not yet have much experience working with it. I feel that it would take some dedicated time to learn the syntax and research the features, performance trade-offs, support, etc.
