### ISSUE TITLE
Error: ETIMEDOUT

### ISSUE THREAD

**Issue by arfianadam** [chill117/proxy-lists#48]
### How to reproduce:
* Fresh install
* `proxy-lists getProxies`

### Log:
```bash
{ Error: ETIMEDOUT
    at Timeout._onTimeout (/home/arfianadam/work/adam/web-bot/node_modules/request/request.js:813:19)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5) code: 'ETIMEDOUT', connect: true }
```
But after some time it returns `Done!` and the proxy list is updated.

**Comment by chill117** [comment]
I just ran the tests and it looks like everything is working right now.

It's possible one of the proxy lists was experiencing some temporary problems, causing the timeout. Errors like that shouldn't prevent you from getting proxies from the other working sources.

**Comment by arfianadam** [comment]
Ah, okay then. Thanks for the reply! Anyway, I was going to add another proxy source. Anything you should mention to me before I look into the code and start replicating?

**Comment by chill117** [comment]
That's great! Pull requests for new sources are very welcome :)

Some suggestions:
* Have a look [here](https://github.com/chill117/proxy-lists#addsource) for technical details on adding a source.
* Please create unit tests for parsing HTML/XML if needed.
* Don't forget about the `series` option. If it's set to `true` then you should run asynchronous operations in series (not parallel). This allows the module to run well with minimal RAM usage if needed.
