### ISSUE TITLE
Get a specific number of proxies

### ISSUE THREAD

**Issue by Rudloff** [chill117/proxy-lists#49]
Hello,

I have a use case where I know the number of proxies I need so it is not very efficient to get the full list just to use a few.
Would it be possible to add an option that sets the number of proxies to return?

**Comment by chill117** [comment]
There is currently the `sample` option which will return some (not all) proxies from each source.

**Comment by Rudloff** [comment]
It's what I currently use but I have a few issues with it:
* `getProxies --sample` will give me ~500 proxies and it's a waste of time to query all these sources if I only need like 20.
* `getProxies --sample -c fr` will give me ~10 proxies (vs. several hundreds without `--sample`) so I might have to query it several times if I need 20.
* In some cases I just want one proxy and don't care about the source but I need a quick response.

**Comment by chill117** [comment]
You can use the `--sources-white-list` option to get proxies from only one specific source. The `--sample` option does limit the number of requests made by each source to the minimum number required to get at least one set of proxies. The response time for each source can vary greatly.

**Comment by Rudloff** [comment]
I found a workaround: I kill the process once I get enough proxies.

**Comment by chill117** [comment]
That works I suppose :)
