### ISSUE TITLE
Disable logs

### ISSUE THREAD

**Issue by Rudloff** [chill117/proxy-lists#52]
Hello,
Is there a way to disable logs when using `--stdout`?
I tried running `proxy-lists getProxies -l /dev/null --stdout` but it seems it always looks for a local file:
```
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open '/media/pierre/Data/www/alltube//dev/null'
    at Error (native)
```

**Comment by chill117** [comment]
Can't really think of a way to do this at the moment. I'll flag this as a feature request.

**Comment by chill117** [comment]
See #62
