### ISSUE TITLE
Error: Missing required option (`option.bitproxies.apiKey`)

### ISSUE THREAD

**Issue by thandonguocmo2020** [chill117/proxy-lists#53]
**proxy-lists getProxies --countries="'us, ca"**

Getting proxies...
Error: Missing required option (`option.bitproxies.apiKey`): You can get an API key for this service by creating an account at https://bitproxies.eu/
Error: Missing required option (`option.kingproxies.apiKey`): You can get an API key for this service by creating an account at https://kingproxies.com/register
Writing output to C:\Users\ADMIN\Desktop\appsearch\myapp/proxies.txt
TypeError: Cannot read property 'toString' of undefined

how to fix error.

**Comment by chill117** [comment]
> Error: Missing required option (option.bitproxies.apiKey): You can get an API key for this service by creating an account at https://bitproxies.eu/
> Error: Missing required option (option.kingproxies.apiKey): You can get an API key for this service by creating an account at https://kingproxies.com/register

You can safely ignore these errors. If you want to get proxies from either of these sources, you will need to create an account at those services and input your API key as an option when using proxy-lists.

> TypeError: Cannot read property 'toString' of undefined

This error is the only one that concerns me. It could be a temporary problem with one of the proxy sources, or one of the source could have changed the structure of their output. I'll have a look when I have some spare time.

**Comment by strech345** [comment]
> and input your API key as an option when using proxy-lists.
And how does the config for this should look like?

**Comment by scramblr** [comment]
there's zero documentation on how to configure API keys from what I can see, can you please explain more?
