### ISSUE TITLE
Some New Proxy Sources

### ISSUE THREAD

**Issue by mnlbox** [chill117/proxy-lists#55]
Hi @chill117 ,
I found this proxy lists recently:

* ~http://proxyfor.eu/geo.php~ -- old proxies
* [x] http://free-proxy-list.net -- already done
* ~http://rebro.weebly.com/proxy-list.html~ -- old proxies
* [x] https://premproxy.com/list/
* ~https://www.proxicity.io/~ -- only gives one proxy at a time

Maybe useful 😉

**Comment by chill117** [comment]
Thanks for these! I don't have much time to implement all of them, but I will try at least some. If anyone else wants to add any of these, pull requests are always welcome :)

**Comment by chill117** [comment]
#61

**Comment by chill117** [comment]
All proxy lists here are either already implemented or don't give new, working proxies.
