### ISSUE TITLE
kingproxies doesn't have free plan, but an error is message is shown if you don't pass in an api key

### ISSUE THREAD

**Issue by josephrocca** [chill117/proxy-lists#58]
The title pretty much says it all. Wouldn't expect to be given an error message if there's no free plan - but maybe you wanted it that way. Just thought I'd let you know in case it's a bug :)

**Comment by chill117** [comment]
I understand what you mean. The reason for the warning message is to inform the user that they won't be gathering proxies from those sources that require an account to get valid proxy data. But I do understand that it can be a bit annoying. Maybe the solution is to add a new option/setting for the proxy-lists module that allows the user to set the verbosity level of the module?

**Comment by josephrocca** [comment]
That would definitely be a nice option to have. Thanks for the module, by the way. It's great!

**Comment by chill117** [comment]
I created a new issue for the new feature idea.
