### ISSUE TITLE
TypeError: options.request is not a function

### ISSUE THREAD

**Issue by RhoidRage** [chill117/proxy-lists#64]
This error always shows when executing "proxy-lists getProxies": TypeError: options.request is not a function

I've tested this on a Windows and Linux machine and the results are the same: The code stops and doesn't write proxies to a text file.

**Comment by RhoidRage** [comment]
This occurs when executing "proxy-lists getProxies"
I've tested this on a Windows and Linux machine and the results are the same: The code stops and doesn't write proxies to a text file.

**Comment by fa7ad** [comment]
Same here

**Comment by chill117** [comment]
Fixed and released v1.14.1
