### ISSUE TITLE
How to get proxies of different countries and cities

### ISSUE THREAD

**Issue by vvbhandare** [chill117/proxy-lists#66]
How to get proxies of different countries and cities?
Do you have any document for the same, if yes please share.

**Comment by chill117** [comment]
Hi @vvbhandare 
This module does not support city-level specificity for geolocation. But you can get proxies based on their country. If you need the city too, I recommend using [node-geoip](https://github.com/bluesmoon/node-geoip) to check each proxy's IP address.

**Comment by chill117** [comment]
Closed as this was answered.
