### ISSUE TITLE
Small fix for proxydb.net

### ISSUE THREAD

**Issue by robjane** [chill117/proxy-lists#73]
https://github.com/chill117/proxy-lists/blob/183991e2efc26604196cb7e26f9393277b64e08c/sources/proxydb.js#L114

```js
                var dataNum = /(data-num[a-z])/g.exec(html.body)[0]
                var portModifier = $(`div[${dataNum}]`).attr(dataNum)
```
I didn't execute your code, but I stole the method in your code to extract proxies from `proxydb.net`. I noted that the last letter in `datanum` is randomized. I supposed this small adjustment might fix it.
If `html.body` exists that is.

**Comment by chill117** [comment]
proxydb fixed-up in latest version
