### ISSUE TITLE
New proxy sources to add

### ISSUE THREAD

**Issue by Oniry** [chill117/proxy-lists#74]
* [x] http://www.workingproxies.org/
* [x] http://www.proxylists.net/
* [x] http://proxy-list.org
* [x] http://www.nntime.com/
* ~http://aliveproxy.com~ (very limited in number of proxies that can be scraped)
* [x] http://tools.rosinstrument.com/proxy/

Part of the resources I found.

**Comment by chill117** [comment]
All useful proxy lists from this issue have been added.
