### ISSUE TITLE
bug?

### ISSUE THREAD

**Issue by jerradpatch** [chill117/proxy-lists#80]
https://github.com/chill117/proxy-lists/blob/2c34b37755b5572dee0cd2e3ba101b94d7200785/index.js#L169

did you mean filter.include  and filter.exclude ?

**Comment by chill117** [comment]
Yes :)

This has been fixed by [this commit](https://github.com/chill117/proxy-lists/commit/cb6c151d720719b14cafd25d824ca81182f6b9ac)
