### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by igrok2016reg** [chill117/proxy-lists#84]
Getting proxies... Writing output to D:\nodejs/proxies.txt Error: unable to verify the first certificate TypeError: Cannot read property 'length' of undefined Error: waiting for selector ".proxytbl tbody tr:not(:first-child)" failed: timeout 30000ms exceeded

8 o'clock. Is it serious?

**Comment by chill117** [comment]
As long as the error doesn't crash the process or otherwise interfere with gathering other proxies, it's fine to ignore.

**Comment by chill117** [comment]
Answered
