### ISSUE TITLE
Not getting any socks proxies

### ISSUE THREAD

**Issue by ledlamp** [chill117/proxy-lists#86]
All proxies I ever get either have no `protocols` property, or `protocols` is `["http"]`.

Example: https://gist.githubusercontent.com/ledlamp/b494b4f1ce13575eeb3ffbbc07fbacf6/raw/5c0ea0dd1375bb94132bc23e05b636828f0eff80/proxies.txt

**Comment by chill117** [comment]
Some of the recently fixed sources only include basic information right now. The master branch includes some changes that will scrape more info like protocol and anonymity-level, but that hasn't been included in a release yet.

**Comment by chill117** [comment]
Released a new version, so you should be getting a decent number of socks proxies now with the following command:
```bash
proxy-lists --protocols="socks4,socks5"
```
