### ISSUE TITLE
Can't get proxies ?

### ISSUE THREAD

**Issue by jerlam06** [chill117/proxy-lists#88]
Hi, here is my code:

```
var ProxyLists = require('proxy-lists');

var options = {
	anonymityLevels: ['elite']
};

// `gettingProxies` is an event emitter object.
var gettingProxies = ProxyLists.getProxies(options);

/* var sources = ProxyLists.listSources();
console.log(sources) */

gettingProxies.on('data', function(proxies) {
	// Received some proxies.
	console.log(proxies);
});

gettingProxies.on('error', function(error) {
	// Some error has occurred.
	console.error(error);
});

gettingProxies.once('end', function() {
	// Done getting proxies.
});
```

Shouldn't this code give me an object of proxies?:

`gettingProxies.on('data', function(proxies) {
	// Received some proxies.
	console.log(proxies);
});`

**Comment by chill117** [comment]
I've tested your code with the latest version of proxy-lists. It appears to be working. Some errors will be printed to the console, but that's normal. You should receive proxies from the sources that are working.
