### ISSUE TITLE
Tests broken

### ISSUE THREAD

**Issue by stylesuxx** [chill117/proxy-lists#99]
Sorry - I must be annoying.
I think something with your tests is broken - if you check out the last build logs on travis, there are only two test cases - both pass, but still, there are more tests to be run - am I missing something?

https://travis-ci.org/chill117/proxy-lists/jobs/557401567

**Comment by chill117** [comment]
Not annoying :) Thank you!

I have removed the `.only` from the mocha test (test/unit/cli.js) that was preventing the other tests from running.
